name: Veracode Static Code Analysis

on:
  workflow_dispatch:
  
jobs:
  create-checks-run:
    name: Create Checks Run
    runs-on: ubuntu-latest
    steps:
      - uses: vincent-deng/veracode-checks-action-ts@main
        name: Create Checks Run
        id: create_checks_run
        with:
          repo: vincentdeng/veracode-checks-action-ts
          token: '123'
          name: Veracode Static Code Analysis
          sha: 'be0dc2992bf6ef3fe20783a9579afdf0be921945'
          status: in_progress
          details_url: https://www.veracode.com