name: Veracode Software Composition Analysis

on:
  push:

jobs:
  veracode-sca-scan:
    runs-on: ubuntu-latest
    name: Veracode Component Analysis

    steps:
      - uses: actions/checkout@v3
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false  
          debug: false
